version: 2.4.{build}
branches:
  only:
  - master
configuration: Release
install:
  - cmd: appveyor DownloadFile https://github.com/nunit/nunit/releases/download/3.0.0-beta-3/nunit-3.0.0-beta-3.zip
  - cmd: 7z x -oC:\Tools\NUnit3 nunit-3.0.0-beta-3.zip > NUL
  - cmd: set PATH=C:\Tools\NUnit3\bin;%PATH%
assembly_info:
  patch: true
  file: '**\ProductAssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: t9gnOzMJGESwOqdD5Tfpv5hmGYPp4TixcGyUPukiO7+6b75pl0RiaABU75GaHQH5
  skip_symbols: true
  on:
    branch: master
    appveyor_repo_tag: true
notifications:
- provider: Email
  to:
  - mattias.nordqvist@spinit.se
  - carl@carl-berg.se
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
